language: python
python:
  - "3.7"

script:
  - python -m doctest pacco/classes_file_based.py -f
  - python -m doctest pacco/remote_manager.py -f
  - git clone https://github.com/sstephenson/bats.git
  - ./bats/install.sh bats_installation
  - export PATH=$PWD/bats_installation/bin:$PATH
  - pip install .
  - bats --tap tests/cli.bats

deploy:
  provider: script
  script: bash scripts/pypi_publish.sh
  on:
    branch: master
